### ISSUE TITLE
Fix save bug when duplicating subsegments

### ISSUE THREAD

**Issue by theolampert** [parkplatz-transform/parkplatztransform-frontend#5]
@henrymoews I'm having a hard time reproducing this again, do you know roughly the steps you took to cause this bug?

**Comment by henrymoews** [comment]
Roughly, yes. But I can't reproduce only later. Roughly:1. Create a new segment or take one without any subsegments.2. Add a subsegment with parking. Use these values:Length 50Car count 20Enable all checkboxes BUT the one about time constraintChoose parking position "middle" and users "car sharing"3. Copy this subsegment, change the length to 20 in the copy4. Now click on save. You should see a confirmation but on page reload everything is gone.Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: [parkplatz-transform/parkplatztransform-frontend] Fix save bug when duplicating subsegments (#5)Von: Theo An: parkplatz-transform/parkplatztransform-frontend Cc: henrymoews ,Mention 
@henrymoews I'm having a hard time reproducing this again, do you know roughly the steps you took to cause this bug?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/parkplatz-transform/parkplatztransform-frontend/issues/5",
"url": "https://github.com/parkplatz-transform/parkplatztransform-frontend/issues/5",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
